-- =============================================================================
-- Migration 0007: Proposal Intelligence and Visual Layer
-- =============================================================================
-- Adds the data model for:
--   • Multi-strategy proposal variants
--   • Low / Mid / High pricing tiers
--   • AI-generated visual prompts / mockup metadata
--   • Company intelligence metadata
--   • Public shareable proposal link (share_token)
--   • Export metadata
-- All new columns are nullable — backward compatible with existing rows.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- proposals: new intelligence and presentation columns
-- ─────────────────────────────────────────────────────────────────────────────

-- strategy_variants: array of alternative strategy objects generated alongside
--   the main proposal content.  Shape: StrategyVariant[] (see schemas.ts).
alter table public.proposals
  add column if not exists strategy_variants jsonb default null;

-- pricing_tiers: structured low/mid/high investment tiers.
--   Shape: PricingTier[] with fields: tier, price_range, activations[],
--   deliverables[], visibility_score, digital_exposure, stadium_exposure.
alter table public.proposals
  add column if not exists pricing_tiers jsonb default null;

-- visual_prompts: AI-generated image-generation prompts and placeholder
--   mockup metadata. Shape: VisualPrompt[] (jersey, banner, board, etc.)
alter table public.proposals
  add column if not exists visual_prompts jsonb default null;

-- intelligence: company intelligence analysis generated by AI.
--   Shape: CompanyIntelligence (marketing_goals, brand_positioning,
--   audience_alignment, sponsorship_fit_score, recommended_direction).
alter table public.proposals
  add column if not exists intelligence jsonb default null;

-- proposal_modules: structured content blocks for the landing page.
--   Shape: ProposalModule[] (hero, stats, strategy, activations, cta …)
alter table public.proposals
  add column if not exists proposal_modules jsonb default null;

-- share_token: random slug for public /proposals/view/[token] page.
--   Null = not yet shared.
alter table public.proposals
  add column if not exists share_token text unique default null;

-- export_metadata: timestamps and links for exported PDF/slides.
alter table public.proposals
  add column if not exists export_metadata jsonb default null;

-- Partial index for fast share-link lookups
create index if not exists proposals_share_token_idx
  on public.proposals (share_token)
  where share_token is not null;

-- ─────────────────────────────────────────────────────────────────────────────
-- companies: intelligence cache
-- ─────────────────────────────────────────────────────────────────────────────

-- company_intelligence: cached AI analysis of the company.
--   Shape: same CompanyIntelligence as above.
alter table public.companies
  add column if not exists intelligence jsonb default null;

-- ─────────────────────────────────────────────────────────────────────────────
-- Bump prompt_version enum value (text column — no enum change needed)
-- ─────────────────────────────────────────────────────────────────────────────
-- prompt_version is already a free-form text column added in migration 0006.
-- The new version v2.0.0 will be set by the application layer.

-- ─────────────────────────────────────────────────────────────────────────────
-- Notify PostgREST to reload schema cache
-- ─────────────────────────────────────────────────────────────────────────────
notify pgrst, 'reload schema';
